name: Deploy to GitHub Pages

on:
  push:
    branches: [ main, master ]
  workflow_dispatch: {}

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare static site (dist)
        run: |
          set -euo pipefail
          mkdir -p dist
          # Root index and static HTMLs
          cp -v index.html dist/
          cp -v .nojekyll dist/ || true
          # Copy all top-level HTML files
          find . -maxdepth 1 -type f -name '*.html' -print -exec cp -v {} dist/ \;

          # Include curated subfolders required by navigation
          # 1) DingPOC static entry and API docs (no backend/client/node_modules)
          mkdir -p dist/DingPOC
          cp -v DingPOC/index.html dist/DingPOC/
          if [ -d "DingPOC/API文檔" ]; then
            mkdir -p "dist/DingPOC/API文檔"
            cp -rv "DingPOC/API文檔/"* "dist/DingPOC/API文檔/"
          fi

          # 2) Other static prototype folders listed in index
          for d in "排班" "黑克松紀錄系統"; do
            if [ -d "$d" ]; then
              mkdir -p "dist/$d"
              cp -rv "$d/"* "dist/$d/"
            fi
          done

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

